---
kind: pipeline
type: docker
name: linux-amd64-debian

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    tags:
      - buster-slim
    dockerfile: debian/Dockerfile
    repo: wryjer/opentracker
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
    - main
  event:
    - push
    - tag

---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    tags: 
      - alpine
      - linux-amd64
      - alpine-linux-amd64
    dockerfile: alpine/Dockerfile
    repo: wryjer/opentracker
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
    - main
  event:
    - push
    - tag

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    tags: 
      - alpine-linux-arm64
      - linux-arm64
    dockerfile: alpine/Dockerfile
    repo: wryjer/opentracker
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
    - main
  event:
    - push
    - tag

depends_on:
  - linux-amd64
